### ISSUE TITLE
Submit on service config last step raises client error

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/einvoice-send#5]
```
(unknown) Unhandled rejection SuperagentPromiseError: cannot PUT /einvoice-send/api/config/inchannel/current (405)
    at executeDispatchesAndRelease (eval at <anonymous> (http://52.233.155.169/einvoice-send/bundle.js:516:1), <anonymous>:43:22)
    at executeDispatchesAndReleaseTopLevel (eval at <anonymous> (http://52.233.155.169/einvoice-send/bundle.js:516:1), <anonymous>:54:10)
    at Array.forEach (native)
    at forEachAccumulated (eval at <anonymous> (http://52.233.155.169/einvoice-send/bundle.js:1467:1), <anonymous>:24:9)
    at runEventQueueInBatch (eval at <anonymous> (http://52.233.155.169/einvoice-send/bundle.js:2976:1), <anonymous>:17:18)
    at Object.handleTopLevel [as _handleTopLevel] (eval at <anonymous> (http://52.233.155.169/einvoice-send/bundle.js:2976:1), <anonymous>:28:5)
```

**Comment by kwierchris** [comment]
The error occurs if not all the data in all tables is removed from the database when testing.

* Remove entry from table **InChannelConfig**.
* Remove related entry from one of the other tables assigned to the same supplierId.

**Comment by kwierchris** [comment]
Is this still the case?

**Comment by nczeranka** [comment]
Never received such an error in the last months. Closed as it seems to be based on inconsistent data after manual SQL deletion (see comment from 7th of June).
